[package]
name = "basic"
version = "0.1.0"
authors = ["Ty Overby <ty@pre-alpha.com>"]
build = "build.rs"

[dependencies.ecsrs]
path = "../../ecsrs"

[build-dependencies.ecsrs-build]
path = "../../ecsrs-build"

[build-dependencies]
latin = "^0.1.3"
